/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/related-projects/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Related Projects */
        post: operations["search_related_projects_api_related_projects_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/related-projects/generate-nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Nodes
         * @description Start node generation; returns a ``job_id`` to poll at ``GET /api/jobs/{id}``.
         *
         *     Generation is long (local LLM), so it runs as a background job rather than
         *     blocking the request. The job result matches ``GenerateNodesResponse``.
         */
        post: operations["generate_nodes_api_related_projects_generate_nodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/taxonomy/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Taxonomy */
        post: operations["generate_taxonomy_api_taxonomy_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projection/surface": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Surface
         * @description Return the precomputed corpus background (grid spec, points, density).
         */
        get: operations["get_surface_api_projection_surface_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projection/locate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Locate
         * @description Embed taxonomy-node text and place each node in the frozen design space.
         */
        post: operations["locate_api_projection_locate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projection/generate-at": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate At
         * @description Start generation seeded by the corpus around a clicked location.
         *
         *     Returns a ``job_id`` immediately; poll ``GET /api/jobs/{job_id}`` for the
         *     result. Generation is long (local LLM), so it runs as a background job rather
         *     than blocking the request (see backend/jobs.py).
         */
        post: operations["generate_at_api_projection_generate_at_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corpus/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Similar Projects
         * @description Closest corpus precedents to a text, ranked by true (original-metric)
         *     cosine similarity — used for design candidates ("my design as a whole is
         *     most like these real projects").
         */
        post: operations["post_similar_projects_api_corpus_similar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corpus/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Corpus Project
         * @description Metadata for one corpus project — the inspectable dots on the design-space surface.
         */
        get: operations["get_corpus_project_api_corpus_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Poll a job: ``{status: pending|done|error, result, detail}``.
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AspectResponse */
        AspectResponse: {
            /** Name */
            name: string;
            /** Desc */
            desc: string;
            /** Options */
            options?: components["schemas"]["OptionResponse"][];
        };
        /**
         * BackendMode
         * @description Selects the LLM/embedding backend used across pipeline commands.
         * @enum {string}
         */
        BackendMode: "openai" | "vllm";
        /**
         * ContentMode
         * @description Selects which text field(s) are used to generate embeddings.
         * @enum {string}
         */
        ContentMode: "description" | "details" | "hybrid" | "all";
        /** CorpusProjectResponse */
        CorpusProjectResponse: {
            /** Id */
            id: string;
            /** Name */
            Name: string;
            /** Descriptions */
            Descriptions: string;
            /** Details */
            Details: string;
            /** Image */
            Image?: string | null;
        };
        /** FetchRelatedProjectsRequest */
        FetchRelatedProjectsRequest: {
            /** Topic */
            topic: string;
            /** Lineage */
            lineage?: string[];
            /** Description */
            description?: string | null;
            /**
             * Should Query Supabase
             * @default true
             */
            should_query_supabase: boolean;
            /**
             * Limit
             * @default 5
             */
            limit: number;
            /**
             * Similarity Threshold
             * @default 0
             */
            similarity_threshold: number;
            /** Embedding Model */
            embedding_model?: string | null;
            /** Match Function */
            match_function?: string | null;
        };
        /** FetchRelatedProjectsResponse */
        FetchRelatedProjectsResponse: {
            /** Projects */
            projects?: components["schemas"]["RelatedProject"][];
        };
        /** FocusNodeInput */
        FocusNodeInput: {
            /** Id */
            id: string;
            /** Topic */
            topic: string;
        };
        /** GenerateAtRequest */
        GenerateAtRequest: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Focus Node Id */
            focus_node_id: string;
            /** Focus Node Topic */
            focus_node_topic: string;
            /** Taxonomy Nodes */
            taxonomy_nodes?: components["schemas"]["backend__projection__router__TaxonomyNodeInput"][];
            /** Lineage */
            lineage?: string[];
            /**
             * K
             * @default 5
             */
            k: number;
            /** Coords */
            coords?: components["schemas"]["NodeCoordInput"][] | null;
            mode?: components["schemas"]["BackendMode"] | null;
            /**
             * Reasoning Effort
             * @default medium
             */
            reasoning_effort: string;
        };
        /** GenerateNodesRequest */
        GenerateNodesRequest: {
            /** Taxonomy Nodes */
            taxonomy_nodes: components["schemas"]["backend__related_projects__router__TaxonomyNodeInput"][];
            focus_node: components["schemas"]["FocusNodeInput"];
            /** Lineage */
            lineage?: string[];
            /** Description */
            description?: string | null;
            /**
             * Should Query Supabase
             * @default true
             */
            should_query_supabase: boolean;
            /** Related Projects */
            related_projects?: components["schemas"]["RelatedProject"][] | null;
            /** Model */
            model?: string | null;
            /** @default openai */
            mode: components["schemas"]["BackendMode"];
            /** Base Url */
            base_url?: string | null;
            /**
             * Reasoning Effort
             * @default medium
             */
            reasoning_effort: string;
        };
        /** GenerateTaxonomyRequest */
        GenerateTaxonomyRequest: {
            /** Project Overview */
            project_overview: string;
            /**
             * Num Reflections
             * @default 1
             */
            num_reflections: number;
            /** @default details */
            content_mode: components["schemas"]["ContentMode"];
            /** Ids File */
            ids_file?: string | null;
            /**
             * Reasoning Effort
             * @default medium
             * @enum {string}
             */
            reasoning_effort: "low" | "medium" | "high";
            /** @default openai */
            mode: components["schemas"]["BackendMode"];
        };
        /** GenerateTaxonomyResponse */
        GenerateTaxonomyResponse: {
            /** Aspects */
            aspects?: components["schemas"]["AspectResponse"][];
            /** Corpus Similarity */
            corpus_similarity?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LocateItem */
        LocateItem: {
            /** Node Id */
            node_id: string;
            /** Text */
            text: string;
        };
        /** LocateRequest */
        LocateRequest: {
            /** Items */
            items?: components["schemas"]["LocateItem"][];
        };
        /** LocateResponse */
        LocateResponse: {
            /** Points */
            points?: components["schemas"]["LocatedPoint"][];
        };
        /** LocatedPoint */
        LocatedPoint: {
            /** Node Id */
            node_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z?: number | null;
            /** Confidence */
            confidence?: number | null;
        };
        /**
         * NodeCoordInput
         * @description A located taxonomy node — lets the backend derive the parent aspect and
         *     the "nearby existing ideas" from the same click that picks the seeds.
         */
        NodeCoordInput: {
            /** Node Id */
            node_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** OptionResponse */
        OptionResponse: {
            /** Name */
            name: string;
            /** Desc */
            desc: string;
        };
        /** RelatedProject */
        RelatedProject: {
            /** Id */
            id?: string | null;
            /** Id */
            Id?: string | null;
            /** Name */
            Name: string;
            /**
             * Descriptions
             * @default
             */
            Descriptions: string;
            /**
             * Details
             * @default
             */
            Details: string;
            /** Image */
            Image?: string | null;
        };
        /** SimilarProject */
        SimilarProject: {
            /** Id */
            id: string;
            /** Name */
            Name: string;
            /** Descriptions */
            Descriptions: string;
            /** Details */
            Details: string;
            /** Image */
            Image?: string | null;
            /** Score */
            score: number;
        };
        /** SimilarProjectsRequest */
        SimilarProjectsRequest: {
            /** Text */
            text: string;
            /**
             * K
             * @default 5
             */
            k: number;
        };
        /** SimilarProjectsResponse */
        SimilarProjectsResponse: {
            /** Projects */
            projects?: components["schemas"]["SimilarProject"][];
        };
        /** SurfaceBounds */
        SurfaceBounds: {
            /** Min */
            min: number;
            /** Max */
            max: number;
        };
        /** SurfaceGrid */
        SurfaceGrid: {
            /** Resolution */
            resolution: number;
        };
        /** SurfacePoint */
        SurfacePoint: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z?: number | null;
            /** Cell */
            cell: number[];
            /** Cluster */
            cluster?: number | null;
            /** Name */
            name?: string | null;
        };
        /** SurfaceResponse */
        SurfaceResponse: {
            /** Version */
            version: number;
            /** Dims */
            dims: number;
            grid: components["schemas"]["SurfaceGrid"];
            bounds: components["schemas"]["SurfaceBounds"];
            /** Density */
            density: number[][];
            /** Points */
            points: components["schemas"]["SurfacePoint"][];
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** TaxonomyNodeInput */
        backend__projection__router__TaxonomyNodeInput: {
            /** Id */
            id: string;
            /** Topic */
            topic: string;
            /** Parentid */
            parentid?: string | null;
            /** Isroot */
            isroot?: boolean | null;
        };
        /** TaxonomyNodeInput */
        backend__related_projects__router__TaxonomyNodeInput: {
            /** Id */
            id: string;
            /** Topic */
            topic: string;
            /** Parentid */
            parentid?: string | null;
            /**
             * Isroot
             * @default false
             */
            isroot: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_related_projects_api_related_projects_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FetchRelatedProjectsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetchRelatedProjectsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_nodes_api_related_projects_generate_nodes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateNodesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_taxonomy_api_taxonomy_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateTaxonomyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateTaxonomyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_surface_api_projection_surface_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurfaceResponse"];
                };
            };
        };
    };
    locate_api_projection_locate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_at_api_projection_generate_at_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateAtRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_similar_projects_api_corpus_similar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimilarProjectsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarProjectsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_corpus_project_api_corpus_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
