/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/related-projects/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Related Projects */
        post: operations["search_related_projects_api_related_projects_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/related-projects/generate-nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Nodes
         * @description Start node generation; returns a ``job_id`` to poll at ``GET /api/jobs/{id}``.
         *
         *     Generation is long (local LLM), so it runs as a background job rather than
         *     blocking the request. The job result matches ``GenerateNodesResponse``.
         */
        post: operations["generate_nodes_api_related_projects_generate_nodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/taxonomy/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Taxonomy */
        post: operations["generate_taxonomy_api_taxonomy_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projection/surface": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Surface
         * @description Return the precomputed corpus background (grid spec, points, density).
         */
        get: operations["get_surface_api_projection_surface_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projection/locate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Locate
         * @description Embed taxonomy-node text and place each node in the frozen design space.
         */
        post: operations["locate_api_projection_locate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projection/peek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Peek
         * @description Gap preview (no LLM, no embedding server): the deterministic seed set a
         *     generate-at would use, nearby already-explored ideas, and the parent aspect
         *     the click would attach to.
         */
        post: operations["peek_api_projection_peek_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projection/axes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Axes
         * @description Exact bipolar coordinates for the semantic-axes perspective: every corpus
         *     project (and any taxonomy/candidate items) scored against two designer-chosen
         *     pole pairs in the original embedding metric.
         */
        post: operations["axes_api_projection_axes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projection/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Metrics
         * @description Score the corpus + items along a list of bipolar metrics — the data
         *     behind the Perspectives profile strips (exact cosine, no projection).
         */
        post: operations["metrics_api_projection_metrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projection/generate-at": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate At
         * @description Start generation seeded by the corpus around a clicked location.
         *
         *     Returns a ``job_id`` immediately; poll ``GET /api/jobs/{job_id}`` for the
         *     result. Generation is long (local LLM), so it runs as a background job rather
         *     than blocking the request (see backend/jobs.py).
         */
        post: operations["generate_at_api_projection_generate_at_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corpus/annotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Annotate
         * @description Annotate the corpus against the taxonomy's options (Halskov-style
         *     schema population, automated — Part 12 A2). Returns a ``job_id``; poll
         *     ``GET /api/jobs/{job_id}``. Cached per option content, so unchanged
         *     options resolve instantly on re-runs.
         */
        post: operations["post_annotate_api_corpus_annotate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corpus/generate-cell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Generate Cell
         * @description Generate ONE concept into an empty option×option cell (the
         *     morphological-combination → candidate-skeleton flow). Returns a
         *     ``job_id``; poll ``GET /api/jobs/{job_id}``.
         */
        post: operations["post_generate_cell_api_corpus_generate_cell_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corpus/rationale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Rationale
         * @description One-line per-aspect rationale ("why this dimension?"), grounded in the
         *     annotation counts. Returns a ``job_id``; poll ``GET /api/jobs/{id}`` →
         *     ``{rationales: {<aspect_id>: str}}``. Cached per aspect content+evidence.
         */
        post: operations["post_rationale_api_corpus_rationale_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corpus/missing-aspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Missing Aspect
         * @description Propose missing aspect(s) from poorly-covered projects. Returns a
         *     ``job_id``; poll ``GET /api/jobs/{id}`` → ``{proposals: [{name, desc,
         *     reason}]}``. Keyed so concurrent probes over the same inputs share a job.
         */
        post: operations["post_missing_aspect_api_corpus_missing_aspect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corpus/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Similar Projects
         * @description Closest corpus precedents to a text, ranked by true (original-metric)
         *     cosine similarity — used for design candidates ("my design as a whole is
         *     most like these real projects").
         */
        post: operations["post_similar_projects_api_corpus_similar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corpus/relevance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Relevance
         * @description True cosine similarity of every corpus project to a text — powers the
         *     design-space relevance lens (scores-only; min/max included so the client
         *     can normalise and label the painting as RELATIVE relevance).
         */
        post: operations["post_relevance_api_corpus_relevance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corpus/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Corpus Project
         * @description Metadata for one corpus project — the inspectable dots on the design-space surface.
         */
        get: operations["get_corpus_project_api_corpus_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/draft-brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Draft Brief
         * @description Draft the candidate's brief from its committed choices (LLM — async job).
         *
         *     Returns ``{job_id}``; poll ``GET /api/jobs/{job_id}``. The result is
         *     ``{brief}`` — a starting point the designer edits, never the final word.
         */
        post: operations["draft_brief_api_candidates_draft_brief_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/steer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Steer
         * @description Steer the brief along a metric / toward a precedent / away from one
         *     (LLM — async job). Returns ``{job_id}``; poll ``GET /api/jobs/{job_id}``.
         *     The result is ``{revised_text, named_qualities, measurement}`` — shown as
         *     a diff for veto, never auto-committed.
         */
        post: operations["steer_api_candidates_steer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/alignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Alignment
         * @description Measure how the candidate's brief (identity) and choices (commitments)
         *     agree — overall and per aspect — in the original embedding metric.
         */
        post: operations["alignment_api_candidates_alignment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reflections/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Draft
         * @description Draft a one-line rationale for an exploration event (async job).
         *     Returns ``{job_id}``; poll ``GET /api/jobs/{id}`` → ``{draft}``.
         */
        post: operations["post_draft_api_reflections_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Poll a job: ``{status: pending|done|error, result, detail}``.
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlignmentAspect */
        AlignmentAspect: {
            /** Aspect Id */
            aspect_id: string;
            chosen: components["schemas"]["AlignmentOption"];
            /** Alternatives */
            alternatives?: components["schemas"]["AlignmentOption"][];
        };
        /** AlignmentAspectResult */
        AlignmentAspectResult: {
            /** Aspect Id */
            aspect_id: string;
            /** Chosen Score */
            chosen_score: number;
            top_alternative?: components["schemas"]["AlignmentTopAlternative"] | null;
            /** Leans Away */
            leans_away: boolean;
        };
        /** AlignmentOption */
        AlignmentOption: {
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /**
         * AlignmentRequest
         * @description The candidate's two layers + the per-aspect option field to score against.
         */
        AlignmentRequest: {
            /** Brief */
            brief: string;
            /** Composition */
            composition: string;
            /** Aspects */
            aspects?: components["schemas"]["AlignmentAspect"][];
        };
        /** AlignmentResponse */
        AlignmentResponse: {
            /** Agreement */
            agreement: number;
            /** Per Aspect */
            per_aspect?: components["schemas"]["AlignmentAspectResult"][];
        };
        /** AlignmentTopAlternative */
        AlignmentTopAlternative: {
            /** Id */
            id: string;
            /** Score */
            score: number;
        };
        /** AnnotateJobResponse */
        AnnotateJobResponse: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
        };
        /** AnnotateOption */
        AnnotateOption: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Desc
             * @default
             */
            desc: string;
        };
        /**
         * AnnotateRequest
         * @description The designer's option set (aspect grouping is irrelevant to membership
         *     judgments, so the request is flat). Part 12 A2.
         */
        AnnotateRequest: {
            /** Options */
            options: components["schemas"]["AnnotateOption"][];
        };
        /** AspectResponse */
        AspectResponse: {
            /** Name */
            name: string;
            /** Desc */
            desc: string;
            /** Options */
            options?: components["schemas"]["OptionResponse"][];
        };
        /** AxesItem */
        AxesItem: {
            /** Node Id */
            node_id: string;
            /** Text */
            text: string;
        };
        /** AxesItemPoint */
        AxesItemPoint: {
            /** Node Id */
            node_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Clipped */
            clipped: boolean;
        };
        /** AxesMeta */
        AxesMeta: {
            /** X Pole Sim */
            x_pole_sim: number;
            /** Y Pole Sim */
            y_pole_sim: number;
            /** Axis Corr */
            axis_corr: number;
        };
        /** AxesPoint */
        AxesPoint: {
            /** Id */
            id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** AxesRequest */
        AxesRequest: {
            x: components["schemas"]["AxisSpec"];
            y: components["schemas"]["AxisSpec"];
            /** Items */
            items?: components["schemas"]["AxesItem"][];
        };
        /** AxesResponse */
        AxesResponse: {
            /** Corpus */
            corpus?: components["schemas"]["AxesPoint"][];
            /** Items */
            items?: components["schemas"]["AxesItemPoint"][];
            meta: components["schemas"]["AxesMeta"];
        };
        /** AxisPole */
        AxisPole: {
            /** Text */
            text: string;
        };
        /** AxisSpec */
        AxisSpec: {
            pole_a: components["schemas"]["AxisPole"];
            pole_b: components["schemas"]["AxisPole"];
        };
        /**
         * BackendMode
         * @description Selects the LLM/embedding backend used across pipeline commands.
         * @enum {string}
         */
        BackendMode: "openai" | "vllm";
        /** CellOption */
        CellOption: {
            /** Name */
            name: string;
            /**
             * Desc
             * @default
             */
            desc: string;
        };
        /**
         * ContentMode
         * @description Selects which text field(s) are used to generate embeddings.
         * @enum {string}
         */
        ContentMode: "description" | "details" | "hybrid" | "all";
        /** CorpusProjectResponse */
        CorpusProjectResponse: {
            /** Id */
            id: string;
            /** Name */
            Name: string;
            /** Descriptions */
            Descriptions: string;
            /** Details */
            Details: string;
            /** Image */
            Image?: string | null;
        };
        /** DraftBriefAspect */
        DraftBriefAspect: {
            /** Aspect */
            aspect: string;
            /** Option */
            option: string;
            /**
             * Desc
             * @default
             */
            desc: string;
        };
        /** DraftBriefRequest */
        DraftBriefRequest: {
            /** Aspects */
            aspects: components["schemas"]["DraftBriefAspect"][];
            /**
             * Project Overview
             * @default
             */
            project_overview: string;
            mode?: components["schemas"]["BackendMode"] | null;
        };
        /** FetchRelatedProjectsRequest */
        FetchRelatedProjectsRequest: {
            /** Topic */
            topic: string;
            /** Lineage */
            lineage?: string[];
            /** Description */
            description?: string | null;
            /**
             * Should Query Supabase
             * @default true
             */
            should_query_supabase: boolean;
            /**
             * Limit
             * @default 5
             */
            limit: number;
            /**
             * Similarity Threshold
             * @default 0
             */
            similarity_threshold: number;
            /** Embedding Model */
            embedding_model?: string | null;
            /** Match Function */
            match_function?: string | null;
        };
        /** FetchRelatedProjectsResponse */
        FetchRelatedProjectsResponse: {
            /** Projects */
            projects?: components["schemas"]["RelatedProject"][];
        };
        /** FocusNodeInput */
        FocusNodeInput: {
            /** Id */
            id: string;
            /** Topic */
            topic: string;
        };
        /** GenerateAtRequest */
        GenerateAtRequest: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Focus Node Id */
            focus_node_id: string;
            /** Focus Node Topic */
            focus_node_topic: string;
            /** Taxonomy Nodes */
            taxonomy_nodes?: components["schemas"]["backend__projection__router__TaxonomyNodeInput"][];
            /** Lineage */
            lineage?: string[];
            /**
             * K
             * @default 5
             */
            k: number;
            /** Coords */
            coords?: components["schemas"]["NodeCoordInput"][] | null;
            mode?: components["schemas"]["BackendMode"] | null;
            /**
             * Reasoning Effort
             * @default medium
             */
            reasoning_effort: string;
            /** Brief */
            brief?: string | null;
        };
        /**
         * GenerateCellRequest
         * @description An empty cross-tab cell (Part 12 B2): two option poles + the
         *     half-matching precedents the frontend already holds from annotation.
         */
        GenerateCellRequest: {
            /** Aspect A */
            aspect_a: string;
            option_a: components["schemas"]["CellOption"];
            /** Aspect B */
            aspect_b: string;
            option_b: components["schemas"]["CellOption"];
            /** Exemplar Ids */
            exemplar_ids?: string[];
        };
        /** GenerateNodesRequest */
        GenerateNodesRequest: {
            /** Taxonomy Nodes */
            taxonomy_nodes: components["schemas"]["backend__related_projects__router__TaxonomyNodeInput"][];
            focus_node: components["schemas"]["FocusNodeInput"];
            /** Lineage */
            lineage?: string[];
            /** Description */
            description?: string | null;
            /**
             * Should Query Supabase
             * @default true
             */
            should_query_supabase: boolean;
            /** Related Projects */
            related_projects?: components["schemas"]["RelatedProject"][] | null;
            /** Model */
            model?: string | null;
            /** @default openai */
            mode: components["schemas"]["BackendMode"];
            /** Base Url */
            base_url?: string | null;
            /**
             * Reasoning Effort
             * @default medium
             */
            reasoning_effort: string;
        };
        /** GenerateTaxonomyRequest */
        GenerateTaxonomyRequest: {
            /** Project Overview */
            project_overview: string;
            /**
             * Num Reflections
             * @default 1
             */
            num_reflections: number;
            /** @default details */
            content_mode: components["schemas"]["ContentMode"];
            /** Ids File */
            ids_file?: string | null;
            /**
             * Reasoning Effort
             * @default medium
             * @enum {string}
             */
            reasoning_effort: "low" | "medium" | "high";
            /** @default openai */
            mode: components["schemas"]["BackendMode"];
        };
        /** GenerateTaxonomyResponse */
        GenerateTaxonomyResponse: {
            /** Aspects */
            aspects?: components["schemas"]["AspectResponse"][];
            /** Corpus Similarity */
            corpus_similarity?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LocateItem */
        LocateItem: {
            /** Node Id */
            node_id: string;
            /** Text */
            text: string;
        };
        /** LocateRequest */
        LocateRequest: {
            /** Items */
            items?: components["schemas"]["LocateItem"][];
        };
        /** LocateResponse */
        LocateResponse: {
            /** Points */
            points?: components["schemas"]["LocatedPoint"][];
        };
        /** LocatedPoint */
        LocatedPoint: {
            /** Node Id */
            node_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z?: number | null;
            /** Confidence */
            confidence?: number | null;
            /**
             * Clipped
             * @default false
             */
            clipped: boolean;
            /** Support */
            support?: number | null;
        };
        /** MetricItemPoint */
        MetricItemPoint: {
            /** Node Id */
            node_id: string;
            /** Score */
            score: number;
            /** Clipped */
            clipped: boolean;
        };
        /** MetricResult */
        MetricResult: {
            /** Corpus */
            corpus: number[];
            /** Items */
            items?: components["schemas"]["MetricItemPoint"][];
            /** Pole Sim */
            pole_sim: number;
        };
        /** MetricSpec */
        MetricSpec: {
            pole_a: components["schemas"]["AxisPole"];
            pole_b: components["schemas"]["AxisPole"];
        };
        /**
         * MetricsRequest
         * @description A LIST of bipolar metrics — the Perspectives strips (generalises /axes).
         */
        MetricsRequest: {
            /** Metrics */
            metrics: components["schemas"]["MetricSpec"][];
            /** Items */
            items?: components["schemas"]["AxesItem"][];
        };
        /** MetricsResponse */
        MetricsResponse: {
            /** Metrics */
            metrics: components["schemas"]["MetricResult"][];
            /** Corr */
            corr: number[][];
        };
        /**
         * MissingAspectRequest
         * @description The coverage probe (Part 13 L-A): the frontend computes which corpus
         *     projects the taxonomy describes poorly; this asks what dimension they
         *     exemplify that the taxonomy misses.
         */
        MissingAspectRequest: {
            /** Aspect Names */
            aspect_names: string[];
            /** Project Ids */
            project_ids: string[];
        };
        /**
         * NodeCoordInput
         * @description A located taxonomy node — lets the backend derive the parent aspect and
         *     the "nearby existing ideas" from the same click that picks the seeds.
         */
        NodeCoordInput: {
            /** Node Id */
            node_id: string;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** OptionResponse */
        OptionResponse: {
            /** Name */
            name: string;
            /** Desc */
            desc: string;
        };
        /** PeekRequest */
        PeekRequest: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /**
             * K
             * @default 5
             */
            k: number;
            /** Taxonomy Nodes */
            taxonomy_nodes?: components["schemas"]["backend__projection__router__TaxonomyNodeInput"][];
            /** Coords */
            coords?: components["schemas"]["NodeCoordInput"][];
        };
        /**
         * PeekResponse
         * @description What a generation at this location would be briefed with — shown to the
         *     designer BEFORE any LLM time is spent.
         */
        PeekResponse: {
            /** Seeds */
            seeds?: components["schemas"]["PeekSeed"][];
            /** Nearby Options */
            nearby_options?: string[];
            /** Parent Aspect */
            parent_aspect?: string | null;
        };
        /** PeekSeed */
        PeekSeed: {
            /** Id */
            id?: string | null;
            /** Name */
            Name: string;
            /**
             * Descriptions
             * @default
             */
            Descriptions: string;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** RationaleAspect */
        RationaleAspect: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Desc
             * @default
             */
            desc: string;
            /** Options */
            options?: components["schemas"]["RationaleOption"][];
        };
        /** RationaleOption */
        RationaleOption: {
            /** Name */
            name: string;
            /** Count */
            count: number;
        };
        /**
         * RationaleRequest
         * @description The taxonomy's aspects with their annotation counts (Part 13 L-A) —
         *     the rationale cites the evidence, so the counts travel with the names.
         */
        RationaleRequest: {
            /** Aspects */
            aspects: components["schemas"]["RationaleAspect"][];
            /**
             * N Projects
             * @default 0
             */
            n_projects: number;
        };
        /** ReflectionDraftRequest */
        ReflectionDraftRequest: {
            /** Context */
            context: string;
        };
        /** RelatedProject */
        RelatedProject: {
            /** Id */
            id?: string | null;
            /** Id */
            Id?: string | null;
            /** Name */
            Name: string;
            /**
             * Descriptions
             * @default
             */
            Descriptions: string;
            /**
             * Details
             * @default
             */
            Details: string;
            /** Image */
            Image?: string | null;
        };
        /** RelevanceRequest */
        RelevanceRequest: {
            /** Text */
            text: string;
        };
        /** RelevanceResponse */
        RelevanceResponse: {
            /** Scores */
            scores?: components["schemas"]["RelevanceScore"][];
            /** Min */
            min: number;
            /** Max */
            max: number;
        };
        /** RelevanceScore */
        RelevanceScore: {
            /** Id */
            id: string;
            /** Score */
            score: number;
        };
        /** SimilarProject */
        SimilarProject: {
            /** Id */
            id: string;
            /** Name */
            Name: string;
            /** Descriptions */
            Descriptions: string;
            /** Details */
            Details: string;
            /** Image */
            Image?: string | null;
            /** Score */
            score: number;
        };
        /** SimilarProjectsRequest */
        SimilarProjectsRequest: {
            /** Text */
            text: string;
            /**
             * K
             * @default 5
             */
            k: number;
        };
        /** SimilarProjectsResponse */
        SimilarProjectsResponse: {
            /** Projects */
            projects?: components["schemas"]["SimilarProject"][];
        };
        /** SteerMetric */
        SteerMetric: {
            /** Pole A Text */
            pole_a_text: string;
            /** Pole B Text */
            pole_b_text: string;
            /** Target Score */
            target_score: number;
        };
        /** SteerReference */
        SteerReference: {
            /** Text */
            text: string;
            /**
             * Weight
             * @default 0.5
             */
            weight: number;
        };
        /**
         * SteerRequest
         * @description One deliberate move on a brief (Part 12 B3). The move is made in
         *     language; the response carries the requested-vs-achieved measurement.
         */
        SteerRequest: {
            /** Text */
            text: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "metric" | "toward" | "away";
            metric?: components["schemas"]["SteerMetric"] | null;
            reference?: components["schemas"]["SteerReference"] | null;
            /** Preserve */
            preserve?: string[];
        };
        /** SurfaceBounds */
        SurfaceBounds: {
            /** Min */
            min: number;
            /** Max */
            max: number;
        };
        /** SurfaceGrid */
        SurfaceGrid: {
            /** Resolution */
            resolution: number;
        };
        /** SurfacePoint */
        SurfacePoint: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z?: number | null;
            /** Cell */
            cell: number[];
            /** Cluster */
            cluster?: number | null;
            /** Name */
            name?: string | null;
        };
        /** SurfaceResponse */
        SurfaceResponse: {
            /** Version */
            version: number;
            /** Dims */
            dims: number;
            grid: components["schemas"]["SurfaceGrid"];
            bounds: components["schemas"]["SurfaceBounds"];
            /** Density */
            density: number[][];
            /** Points */
            points: components["schemas"]["SurfacePoint"][];
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** TaxonomyNodeInput */
        backend__projection__router__TaxonomyNodeInput: {
            /** Id */
            id: string;
            /** Topic */
            topic: string;
            /** Parentid */
            parentid?: string | null;
            /** Isroot */
            isroot?: boolean | null;
        };
        /** TaxonomyNodeInput */
        backend__related_projects__router__TaxonomyNodeInput: {
            /** Id */
            id: string;
            /** Topic */
            topic: string;
            /** Parentid */
            parentid?: string | null;
            /**
             * Isroot
             * @default false
             */
            isroot: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_related_projects_api_related_projects_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FetchRelatedProjectsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetchRelatedProjectsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_nodes_api_related_projects_generate_nodes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateNodesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_taxonomy_api_taxonomy_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateTaxonomyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateTaxonomyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_surface_api_projection_surface_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurfaceResponse"];
                };
            };
        };
    };
    locate_api_projection_locate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    peek_api_projection_peek_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeekRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeekResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    axes_api_projection_axes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AxesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AxesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_projection_metrics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetricsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_at_api_projection_generate_at_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateAtRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_annotate_api_corpus_annotate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnotateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnotateJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_generate_cell_api_corpus_generate_cell_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateCellRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnotateJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_rationale_api_corpus_rationale_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RationaleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnotateJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_missing_aspect_api_corpus_missing_aspect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissingAspectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnotateJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_similar_projects_api_corpus_similar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimilarProjectsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarProjectsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_relevance_api_corpus_relevance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelevanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelevanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_corpus_project_api_corpus_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_brief_api_candidates_draft_brief_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftBriefRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    steer_api_candidates_steer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SteerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alignment_api_candidates_alignment_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlignmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlignmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_draft_api_reflections_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReflectionDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
